name: OxRacing Android Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  buildAndroid:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Unity Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-OxRacing-${{ hashFiles('ProjectSettings/ProjectVersion.txt') }}
          restore-keys: |
            Library-OxRacing-

      - name: Build Android APK
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: .
          targetPlatform: Android
          unityVersion: 6000.0.43f1
          androidExportType: androidPackage
          buildMethod: OxRacing.Editor.BuildScript.BuildAndroid

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: OxRacing-Android-APK
          path: build/Android/*.apk
